name: ccbclibrary
description: Nepali Christian Teachings - बाइबलबाट पाठहरु

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+12

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  get_storage: ^2.0.2
  share: ^2.0.4
  url_launcher: ^6.0.9
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  permission_handler: ^8.1.3
  flutter_downloader: ^1.6.1
  firebase_core: ^1.4.0
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.0
  audio_service: ^0.17.1
  just_audio: ^0.7.5
  audio_session: ^0.1.5
  rxdart: ^0.27.1
  glass: ^1.0.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_spinkit: ^5.0.0
  connectivity: ^3.0.6
  ext_storage:
    git:
      url: git://github.com/GitJournal/ext_storage.git

  facebook_audience_network: ^1.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^0.14.1+1
  json_serializable: ^4.1.3

#  flutter_launcher_icons: ^0.9.0
#flutter_icons:
#  android: true
#  ios: false
#  image_path: "assets/icon/squareicon.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/background/
     - assets/images/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


#flutter packages pub run build_runner watch --delete-conflicting-outputs
#flutter packages pub run build_runner build --delete-conflicting-outputs